apiVersion: v1
kind: Service
metadata:
  name: {{ include "consumer.fullname" . }}
spec:
  selector:
    app: {{ include "consumer.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}

