{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kafka-hpa
  namespace: {{ .Values.kafka.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ .Values.kafka.name }}-kafka
  minReplicas: {{ .Values.hpa.kafka.minReplicas }}
  maxReplicas: {{ .Values.hpa.kafka.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.kafka.cpu.targetAverageUtilization }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: zookeeper-hpa
  namespace: {{ .Values.kafka.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ .Values.kafka.name }}-zookeeper
  minReplicas: {{ .Values.hpa.zookeeper.minReplicas }}
  maxReplicas: {{ .Values.hpa.zookeeper.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.zookeeper.cpu.targetAverageUtilization }}
{{- end }}

