apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "producer.fullname" . }}
  labels:
    app: {{ include "producer.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "producer.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "producer.name" . }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ include "producer.name" . }}
            topologyKey: kubernetes.io/hostname
      containers:
      - name: producer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "{{ .Values.kafkaBootstrapServers }}"

