apiVersion: v1
kind: Service
metadata:
  name: {{ include "producer.fullname" . }}
spec:
  selector:
    app: {{ include "producer.name" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}

